### ISSUE TITLE
Changing "JSON Object containing file name as key and the letter as value" textarea does not change the generated keys

### ISSUE THREAD

**Issue by rafaeldolfe** [NetroScript/Input-Button-Sprite-Generator#1]
Lovely git repo! For those who just want to generate sprites without cloning the repo and so on, it would be mighty useful if changing the json directly in [the website](https://netroscript.github.io/Input-Button-Sprite-Generator/) would also cause it to generate different sprites. This should be as easy as reading from the text area using an id.

As a workaround right now, it is possible to directly modify the main.js code in the inspector. Just modify the `defaultKeyDict` dictionary at the beginning of the function `generateKeyImages`, for example

`defaultKeyDict = {
      "KEY_LEFTSHIFT": "LeftShift",
      "KEY_SPACEBAR": "Spacebar",
      "KEY_W": "W",
      "KEY_A": "A",
      "KEY_S": "S",
      "KEY_D": "D"
    }`

**Comment by NetroScript** [comment]
Oh well, it was always intended that you can edit the dictionary, that's why an editable textarea is used.

But it seems I forgot to add the code so that this functionality actually works 😅.

I added this functionality now in 181a4a53879ba7460603cfb866ca19d62ceaa3e5 and additionally updated the dependency.
